version: 2.1
orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.1-stretch-node
      auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
workflows:
  version: 2
  build:     
    jobs:
      - build
